-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url VARCHAR(30),
  rating 3,
  desc 
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (id, title, url, rating, desc)
values
  ('Sam', '555-1234'),
  ('Ham', '555-4321'),
  ('Ram', '555-5678');